networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/loki.yml
    volumes:
      # - type: volume
      #   source: prometheus-storage
      #   target: /prometheus
      - type: bind
        source: ./loki
        target: /etc/loki
    networks:
      - loki
    ports:
      - 3100:3100

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki