services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=12w'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?err}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?err}
    volumes:
      - type: volume
        source: prometheus-storage
        target: /prometheus
      - type: bind
        source: ./prometheus
        target: /etc/prometheus
    networks:
      - backend
    ports:
      - 9090:9090
    restart: unless-stopped


  grafana:
    image: grafana/grafana:latest
    volumes:
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
      - type: bind
        source: ./grafana/provisioning
        target: /etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped


volumes:
  prometheus-storage: {}
  grafana-storage: {}


networks:
  backend:
    driver: bridge
