x-base-config: &base-config
  networks:
    - backend
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: '5'
      compress: 'true'

services:
  loki:
    image: grafana/loki:2.9.1
    command: -config.file=/etc/loki/loki-unity.yml -print-config-stderr
    volumes:
      - type: volume
        source: loki-storage
        target: /loki
      - type: bind
        source: ./loki
        target: /etc/loki
    ports:
      - 3100:3100
    restart: unless-stopped
    <<: *base-config

volumes:
  loki-storage: { }

networks:
  backend:
    driver: bridge
