services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/loki.yml -print-config-stderr
    volumes:
      - type: volume
        source: loki-storage
        target: /loki
      - type: bind
        source: ./loki
        target: /etc/loki
    networks:
      - loki
    ports:
      - 3100:3100

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

volumes:
  loki-storage: {}

networks:
  loki: