# - targets:
#     - host.docker.internal:9100
#   labels:
#     file_sd_type: local

# - targets:
#     - 16.163.105.199:9100
#   labels:
#     file_sd_type: aws

# - targets:
#     - 103.147.199.16:9100
#   labels:
#     file_sd_type: teson
