# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: file-sd

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    file_sd_configs:
      # Patterns for files from which target groups are extracted.
      - files:
          - file-sd.yml
        refresh_interval: 5m

  - job_name: aws
    ec2_sd_configs:
      - region: 'ap-east-1' # The AWS region. If blank, the region from the instance metadata is used. The AWS API keys. If blank, the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are used.
        port: 9100
        refresh_interval: 15s # Refresh interval to re-read the instance list.
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip, port]
        separator: ':'
        target_label: __address__
      - source_labels: [__meta_ec2_tag_Name, __meta_ec2_public_ip]
        separator: ':'
        target_label: instance
      - source_labels: [__meta_ec2_instance_state] # Ignore stopped instance
        regex: stopped
        action: drop


