global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yaml"
  # - "second_rules.yaml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: pqs-lom
    file_sd_configs:
      - files:
          - pqs-lom-file-sd.yaml
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__] # Set port here instead of in file sd yaml.
        target_label: instance
        replacement: game-server:${1}
      - source_labels: [__address__] # Set port here instead of in file sd yaml.
        target_label: __address__
        replacement: ${1}:9100

  - job_name: agones
    file_sd_configs:
      - files:
          - agones-file-sd.yaml
        refresh_interval: 1m

  - job_name: redis
    file_sd_configs:
      - files:
          - redis-file-sd.yaml
        refresh_interval: 1m

  - job_name: test
    file_sd_configs:
      - files:
          - test-file-sd.yaml
        refresh_interval: 1m

  - job_name: minio-lom
    metrics_path: /minio/v2/metrics/cluster
    scheme: https
    file_sd_configs:
      - files:
          - minio-lom-file-sd.yaml
        refresh_interval: 1m

  - job_name: minio-dev
    metrics_path: /minio/v2/metrics/cluster
    scheme: https
    file_sd_configs:
      - files:
          - minio-dev-file-sd.yaml
        refresh_interval: 1m

  - job_name: aws-development
    ec2_sd_configs:
      - region: 'ap-east-1'
        role_arn: 'arn:aws:iam::787649184717:role/PrometheusRole'
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip] # Default addresses are all private ips, have to overwrite with public ip so we can reach the target.
        target_label: __address__
        replacement: ${1}:9100
      - source_labels: [__meta_ec2_tag_Name, __meta_ec2_public_ip]
        separator: ':'
        target_label: instance
      - source_labels: [__meta_ec2_instance_state] # Ignore stopped instance
        regex: stopped
        action: drop
      - replacement: staging
        target_label: environment

  - job_name: aws-lom
    ec2_sd_configs:
      - region: 'ap-east-1'
        role_arn: 'arn:aws:iam::827877038561:role/PrometheusRole'
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip] # Default addresses are all private ips, have to overwrite with public ip so we can reach the target.
        target_label: __address__
        replacement: ${1}:9100
      - source_labels: [__meta_ec2_tag_Name, __meta_ec2_public_ip]
        separator: ':'
        target_label: instance
      - source_labels: [__meta_ec2_instance_state] # Ignore stopped instance
        regex: stopped
        action: drop
      - replacement: production
        target_label: environment


