- targets:
    - 34.80.4.95:9100
  labels:
    instance: match-server:34.80.4.95
    environment: staging

- targets:
    - 34.80.66.188:9100
  labels:
    instance: match-server:34.80.66.188
    environment: production