- targets:
    - 103.147.199.7:9100
  labels:
    instance: grafana:103.147.199.7
    environment: production

- targets:
    - 34.80.4.95:9100
  labels:
    instance: match-server:34.80.4.95
    environment: staging

- targets:
    - 34.80.66.188:9100
  labels:
    instance: match-server:34.80.66.188
    environment: production

- targets:
    - 103.137.246.213:9100
  labels:
    instance: minio:103.137.246.213
    environment: staging

- targets:
    - 103.137.246.214:9100
  labels:
    instance: minio:103.137.246.214
    environment: staging

- targets:
    - 103.137.246.215:9100
  labels:
    instance: minio:103.137.246.215
    environment: production

- targets:
    - 103.137.246.216:9100
  labels:
    instance: minio:103.137.246.216
    environment: production
